[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "askify-cli"
version = "0.1.0"
description = "Know your stuff - Chat with your code and documents from the terminal"
requires-python = ">=3.10"
dependencies = [
    "typer",
    "groq",
    "chromadb",
    "sentence-transformers",
    "pymupdf",
    "python-dotenv",
    "rich",
    "python-docx"
]

[project.scripts]
askify = "askify.cli:app"

[tool.setuptools.packages.find]
where = ["."]